version: "3.10"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=main.py
      - FLASK_DEBUG=TRUE
    command: flask run --host=0.0.0.0
